communication/urls.py
from django.urls import path

from . import views

app_name = 'communication'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_communication, name='new'),
    
    
]

core/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views


from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='core/logout.html'), name='logout')
    
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    
]

item/urls.py
from django.urls import path 


from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('category/<int:category_id>/', views.itemsca, name='itemsca'),
]

test_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('communication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories':categories,
        'items':items
    })
    
def contact(request):
    return render(request, 'core/contact.html')

def about(request):
    return render(request, 'core/about.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
    
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

@login_required
def logout(request):
    
    return redirect('/login/')

core/templates/core/about.html
{% extends 'core/base.html'%}

{% block title %}
    Contact
{% endblock %}


{% block content %}
    <h1 class="mb-12 text-4xl text-center font-bold tracking-wide border-b-4 border-teal-300">About Us </h1>
    <p class="text-xl mr-10 ml-10">
         Introducing our mini online shop, a haven for those seeking to declutter their lives and discover hidden treasures. Our platform provides a convenient and user-friendly marketplace for people to sell their gently used items, from clothing and electronics to furniture and collectibles. We believe in the power of reuse and sustainability, and our mission is to connect sellers with eager buyers who appreciate the value of pre-loved goods. Whether you're looking to make some extra cash by selling items you no longer need or on the hunt for unique finds at affordable prices, our mini online shop is the ideal destination for both buyers and sellers alike. Join us in reducing waste and promoting responsible consumerism while exploring a world of secondhand gems.</p>
{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>
    
   <title>{% block title %}
    {% endblock %} | Django
    </title> 
</head>
<body>
    <nav class="py-3 px-6 flex justify-between items-center border-b border-gray-200 ">
        <div  style=" width: 100px;"><a href="/" class="text-xl font-semibold"><img src="../../../media/items_images/LogoM2-PhotoRoom.png-PhotoRoom.png"/></a></div>
        <div class="space-x-6 flex">
            <a href="{% url 'item:new' %}" class="mt-3 text-lg font-semibold hover:text-gray-500">New item</a> 
            <a href="{% url 'item:items' %}" class="mt-3 text-lg font-semibold hover:text-gray-500">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    class="h-7 w-7">
                    <path
                    fill-rule="evenodd"
                    d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z"
                    clip-rule="evenodd" />
                </svg>
            </a>  

            {% if request.user.is_authenticated %}
            <a href="{% url 'communication:inbox' %}" class="py-3 px-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a> 
            <a href="{% url 'dashboard:index' %}" class="py-3 px-6 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            <a href="{% url 'core:logout' %}" class="py-3 px-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">logout</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="py-3 px-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a> 
            <a href="{% url 'core:login' %}" class="py-3 px-6 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a> 
            {% endif %}
        </div>
    </nav>
    
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <div class="bg-white"  style=" width: 100px;"><a href="/" class="text-xl font-semibold " ><img src="../../../media/items_images/LogoM2-PhotoRoom.png-PhotoRoom.png"/></a></div>

            <p class="text-lg text-gray-500">Discover the beauty in second chances, where pre-loved items find new homes.</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>
</body>

</html>

core/templates/core/contact.html
{% extends 'core/base.html'%}

{% block title %}
    Contact
{% endblock %}


{% block content %}
    <h1>Contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html'%}

{% block title %}
    Welcome
{% endblock %}


{% block content %}

<div class="px-6 py-20 text-center md:px-12 lg:text-left">
    <div class="w-100 mx-auto sm:max-w-2xl md:max-w-3xl lg:max-w-5xl xl:max-w-7xl">
      <div class="grid items-center gap-12 lg:grid-cols-2">
        <div class="mt-12 lg:mt-0">
            <h1 class="mt-6 mb-10 text-9xl font-bold tracking-tight">
                Mercato
            </h1>
          <h2 class="mt-0 mb-16 text-6xl font-bold tracking-tight text-gray-500">
            The best offers <br /><span class="text-teal-500">for your needs</span>
          </h2>
        </div>
        <div class="mb-12 lg:mb-0">
          <img src="https://tecdn.b-cdn.net/img/new/ecommerce/horizontal/048.jpg"
            class="w-full rounded-lg shadow-lg dark:shadow-black/20" alt="" />
        </div>
      </div>
    </div>
  </div>
  
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        
        <h2 class="mb-12 text-4xl text-center font-bold tracking-wide border-b-4 border-teal-300">Newest items</h2>
        
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl" />
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a> 
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-4xl text-center font-bold tracking-wide border-b-4 border-teal-300">Categories</h2>
        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                <a href="{% url 'item:itemsca' category.id %}">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{category.name}}</h2>
                        <p class="text-gray-500">{{category.items.count}} items</p>
                    </div>
                </a> 
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
    Login
{% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>

        <form method="post" action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
    Sign up
{% endblock %}


{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Confirm Password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}